site_name: Tips for CP4D and OpenShift (Public)
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
  features:
    - navigation.indexes
  logo: img/icp4data_blanc.svg
  favicon: img/favicon.png
nav:
    - Home: index.md
    - Db2 on ROKS Gen2 : db2-roks.md
    - Openshift Client : oc-client-install.md
markdown_extensions:
    - attr_list
extra:
  social:
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/ronanbourlier/
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/infrarchitect
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
copyright: Copyright &copy; 2022 IBM - Ronan Bourlier
