site_name: Tips for CP4D and OpenShift
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
nav:
    - Home: index.md
    - Db2 on ROKS Gen2 : db2-roks.md
markdown_extensions:
    - attr_list
