site_name: CP4D installation on TEC
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
nav:
    - Home: index.md
    - TEC: tec.md
    - CP4D 2.5: CP4D2.5.md
    - CP4D 3.0: CP4D3.0.md
markdown_extensions:
    - attr_list
